package db

import (
	"database/sql"
	"log"
	"os"
	"testing"

	_ "github.com/lib/pq"
)

var testQueries *Queries
var testDBConn *sql.DB

const (
	dbDriver = "postgres"
	dbSource = "postgres://root:secret@localhost:5432/bank?sslmode=disable"
)

func TestMain(m *testing.M) {
	var err error
	testDBConn, err = sql.Open(dbDriver, dbSource)
	if err != nil {
		log.Fatal("cannot connect to db:", err)
	}

	//use the New function generated by sqlc to create a new db with our connection string
	testQueries = New(testDBConn)

	//Run the unit test
	os.Exit(m.Run())
}
